# Generated by Django 4.2.21 on 2026-03-11 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('target_date', models.DateField(verbose_name='目標日')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '完了'), ('archived', 'アーカイブ')], default='active', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習計画',
                'verbose_name_plural': '学習計画一覧',
                'db_table': 'plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
