# Generated by Django 4.2.21 on 2026-03-11 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('status', models.CharField(choices=[('pending', '未着手'), ('in_progress', '進行中'), ('completed', '完了')], default='pending', max_length=20, verbose_name='ステータス')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.planmodel', verbose_name='学習計画')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク一覧',
                'db_table': 'tasks',
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
