# Generated by Django 4.2.21 on 2026-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='actual_dates',
            field=models.JSONField(default=list, verbose_name='実績日付リスト'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='plan_dates',
            field=models.JSONField(default=list, verbose_name='計画日付リスト'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
