# Generated by Django 4.2.21 on 2026-03-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(verbose_name='予定日時')),
                ('memo', models.TextField(blank=True, default='', verbose_name='事前メモ')),
                ('summary', models.TextField(blank=True, default='', verbose_name='セッションまとめ')),
                ('status', models.CharField(choices=[('scheduled', '予定済み'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='scheduled', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'セッション',
                'verbose_name_plural': 'セッション一覧',
                'db_table': 'sessions',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
